### ISSUE TITLE
Arc furnace metal powder exploit

### ISSUE THREAD

**Issue by TimovVeen** [NMagpie/TFC-IE-Crossover#15]
Hello,
There is a conflict in recipes for all copper and iron powders in the arc furnace.
![image](https://github.com/NMagpie/TFC-IE-Crossover/assets/104511421/709f5209-f0b8-47ee-8012-6355c207b793)
In this screenshot, the top recipe is added by IE, accepting any item with the forge copper dust tag. The intended recipe added by this mod is below. Since native copper powder in this case has the forge tag, you can convert 1 dust into 1 ingot. As a 20x increase in efficiency is a pretty big exploit, I think the IE recipe should be removed for copper and wrought iron ingots.
Thanks. Great mod

**Comment by HermitOwO** [comment]
I'd say that's a problem on TFC's side because the forge tag is added but not used anywhere. There was a conversation at the TFC discord and Alc agreed that there is no benefit from tagging the powders as forge dusts. I guess they forgot to remove the tag afterwards. I will make a PR to change that.

**Comment by TimovVeen** [comment]
Ah I see, if there's no reason for them to have the tag, then that's a better solution. Thank you
